// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV2Y61lf0lOR2IiuutU3q2gwWLNp9nDZw',
    appId: '1:814993951002:web:af8e9830296230efa484a3',
    messagingSenderId: '814993951002',
    projectId: 'instagram-9b107',
    authDomain: 'instagram-9b107.firebaseapp.com',
    storageBucket: 'instagram-9b107.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxs8gp4CfH_VveoHm62-IVU63whup0C4Q',
    appId: '1:814993951002:android:b0f7c9449cf5161ea484a3',
    messagingSenderId: '814993951002',
    projectId: 'instagram-9b107',
    storageBucket: 'instagram-9b107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdj12xr38UaOOH_zUsJbnXZFU4eNG5b-E',
    appId: '1:814993951002:ios:0a58b60d8fcf3aa6a484a3',
    messagingSenderId: '814993951002',
    projectId: 'instagram-9b107',
    storageBucket: 'instagram-9b107.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdj12xr38UaOOH_zUsJbnXZFU4eNG5b-E',
    appId: '1:814993951002:ios:0a58b60d8fcf3aa6a484a3',
    messagingSenderId: '814993951002',
    projectId: 'instagram-9b107',
    storageBucket: 'instagram-9b107.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV2Y61lf0lOR2IiuutU3q2gwWLNp9nDZw',
    appId: '1:814993951002:web:036657b2f0f1062da484a3',
    messagingSenderId: '814993951002',
    projectId: 'instagram-9b107',
    authDomain: 'instagram-9b107.firebaseapp.com',
    storageBucket: 'instagram-9b107.appspot.com',
  );
}
